name: "Newman tests"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
     container:
        image: postman/newman
    steps:
      - name: Checkout
        uses: actions/setup-node@v2
      - name: Run API Tests
        run: newman run "RestfulBookerBVT.postman_collection.json" -e Local.postman_environment.json
